### ISSUE TITLE
no `TransformerWeights` in `model`

### ISSUE THREAD

**Issue by sunnyregion** [srush/llama2.rs#38]
use crate::model::TransformerWeights;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TransformerWeights` in `model`

**Comment by sunnyregion** [comment]
llama2.rs$ tree src
src
├── constants.rs
├── gptq_cuda.rs
├── gptq.ptx
├── gptq.rs
├── gptq_test.rs
├── inference.rs
├── kernel.py
├── lib.rs
├── main.rs
├── models.rs
├── tokenizer.rs
└── util.rs

0 directories, 12 files

**Comment by srush** [comment]
good catch, missed a file. Should be fixed now, let me check the CI. 

https://github.com/srush/llama2.rs/pull/39

**Comment by sunnyregion** [comment]
thx a lot
