### ISSUE TITLE
readme commands does'nt work 

### ISSUE THREAD

**Issue by AsureDay** [srush/llama2.rs#6]
* There is no command for install llama2-70b-q.bin and does'nt work

`bash pip install torch transformers [auto-gptq](https://github.com/PanQiWei/AutoGPTQ)
python export.py llama2-70b-q.bin`

* this works

`bash pip install torch transformers auto-gptq
python export.py llama2-70b-q.bin`

**Comment by srush** [comment]
Fixed! We're you able to get it to run?
